### PR TITLE
Resolve RUSTSEC-2020-0071 by removing time 0.1 dependency from chrono

### PR DESCRIPTION
**Pull request by kpcyrd**
Also upgrades two dependencies

### CODE REVIEW

**Comment by adityasaky** [comment]
Thanks @kpcyrd! Side note, I just realized we don't have dependabot configured here.

**Comment by kpcyrd** [comment]
Thanks for the fast merge! :)

**Comment by kpcyrd** [comment]
hi! :D could you release a new version with this change (either 0.3.1 or 0.4.0)?

Thanks!

**Comment by adityasaky** [comment]
Hey @kpcyrd, I'll try and have 0.4.0 out soon. I just opened https://github.com/in-toto/in-toto-rs/pull/55. Is it okay to have that merged and dependencies bumped before the release?

**Comment by kpcyrd** [comment]
Yes sure :)

**Comment by adityasaky** [comment]
Hey @kpcyrd: https://github.com/in-toto/in-toto-rs/releases/tag/v0.3.1, https://crates.io/crates/in-toto

v0.3.1 is live!

**Comment by kpcyrd** [comment]
Thanks, running `cargo update` and pushing the new Cargo.lock has resolved my dependabot alert! :)

image

**Pull request merged**
