### PR TITLE
fix: compatibility of key id calculation with python in-toto

### PR DESCRIPTION
**Pull request by Xynnn007**
#### Background
Materials of hash functions to calculate key id should be the whole PEM-encoded PKIX public key with "\r\n " replaced by "\n". 

#### Change Log

- Fixed the bug mentioned above to work consistently with python/golang-in-toto
- Fixed related test cases using the new `key_id` generation algorithm
- Added a unit test to compare keyid generated by in-toto-rs with the demo in
https://github.com/in-toto/demo

### CODE REVIEW

**Comment by Xynnn007** [comment]
The CI error reported is not related to this PR. I will open another PR to fix this.

**Comment by Xynnn007** [comment]
Please **DO NOT** start review this until https://github.com/in-toto/in-toto-rs/pull/39 is merged.

**Comment by adityasaky** [comment]
#39 is merged, I think this can be rebased now. :)

**Review by adityasaky — APPROVED** [review]
The code looks fine to me but @SantiagoTorres can you double check? Thanks!

**Review by mlieberman85 — APPROVED** [review]
LGTM

**Comment by adityasaky** [comment]
Thanks for the patch, @Xynnn007!

**Pull request merged**
